### ISSUE TITLE
Don't use css ids

### ISSUE THREAD

**Issue by saily** [plone/plone.login#29]
As csslint reports and all plone users hate, we should get rid of using css ids for all our customization stuff and specially styling. The disadvantage is that integrators have to hack around with `!important` or css load order to get this stuff overridden. 

Clean up the css code and use just simple css classes.

**Comment by petri** [comment]
From what I understand, after reading various articles on this, it seems to me using ids is (still) quite ok if there is little chance that there will be elements requiring same styling (as the element with the id). 

So if the login form has elements that are conceivably guaranteed to be unique, there is nothing wrong about using ids. I would assume there certainly are, but I may be wrong. If there are no (semantically) unique elements, then ids may well be useless and should perhaps be avoided.

FWIW, if CSSlint complains that does not mean something is definitely wrong. Often the checker tools by default complain overeagerly to satisfy the 80/20 rule (assume something is always wrong because it's wrong 80% of the time).
