### ISSUE TITLE
do we need wrapped forms?

### ISSUE THREAD

**Issue by ableeb** [plone/plone.login#31]
Removing them would make customizing the login forms more consistent with the rest of Plone - developers/integrators would be able to use zcml metaconfiguration. see #27 for discussion

**Comment by pbauer** [comment]
We started looking at what is neccessary to finish plone.login and we're wondering about the state of the branches https://github.com/plone/plone.login/compare/unwrap_forms and https://github.com/plone/plone.login/compare/login-help-unwrapped. 

It seems like it is not possible to override for example the login-form with z3c.jbot when using the master-branch. Using the unwrapped forms it seems possible but the forms seem broken (among other things the styles are lost). 

Do I get it right that the preferred method of overriding is still to use FormTemplateFactory() and using jbot is not an option?

@ableeb @saily: Since the two branches mentioned above are not merged: Is the attempt to unwrap these forms obsolete?

**Comment by ableeb** [comment]
@pbauer my intention was to provide a standard way to override the login forms via jbot, consistent with the Plone theming story. This led to working on the (unfinished) un-wrapped forms branch. While I was working on that, @saily implemented a working implementation  which was merged into master.   

That said, I think the optimal solution is to have plone.login part of the overall Plone theming story, customizable via jbot/zcml. As its been most of 3 years since I last worked on it, I don't recall how much more effort it would take to get there.   

To answer your questions:
1.  Currently yes, but I think it would be better to have it customizeable via jbot.
1. Maybe not obsolete, but definitely needs work!

**Comment by agitator** [comment]
@ableeb is absolutely right, customizability with z3c.jbot is a must and that is not the case right now

**Comment by pbauer** [comment]
I agree, I was pondering that thought lately and came to the same conclusion that we should unwrap the forms and make them customizable with jbot. 

Since I am busy with other tasks I cannot work on this currently but I'd welcome an attempt to revive the changes in these branches before plone.login is merged into core.

**Comment by ableeb** [comment]
@pbauer @agitator 👍

**Comment by jensens** [comment]
see PR #48

**Comment by agitator** [comment]
fixed with https://github.com/plone/plone.login/pull/48
